# Generated by Django 3.2.12 on 2023-02-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
