# Generated by Django 3.2.12 on 2023-02-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0004_auto_20230208_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cat', models.CharField(max_length=100)),
                ('descripcion_cat', models.TextField(blank=True)),
                ('fecha_creacion_cat', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion_cat', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
