# Generated by Django 3.2.12 on 2023-02-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0010_auto_20230226_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_cart',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='item_cart',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Item_Cart',
        ),
    ]
