# Generated by Django 3.2.12 on 2023-02-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0012_cart_item_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_cart',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='Negocio.cart'),
        ),
        migrations.AlterField(
            model_name='item_cart',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Negocio.producto'),
        ),
    ]
