# Generated by Django 3.2.12 on 2023-03-04 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Negocio', '0013_auto_20230226_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre_cat',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='nombre_des',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre_mar',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre_mat',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card', models.CharField(max_length=16)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('cvv', models.CharField(max_length=4)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
